name: Build Firefox

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-firefox:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Firefox build can be long, increase if needed

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        repository: mozilla/gecko-dev
        depth: 1

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y autoconf2.13 yasm libasound2-dev libcurl4-openssl-dev libdbus-1-dev libdbus-glib-1-dev libgtk-3-dev libpulse-dev libx11-xcb-dev libxt-dev mesa-common-dev python3 python3-pip unzip zip

    - name: Create mozconfig
      run: |
        echo "ac_add_options --enable-application=browser" > mozconfig
        echo "ac_add_options --enable-optimize" >> mozconfig
        echo "mk_add_options MOZ_MAKE_FLAGS='-j$(nproc)'" >> mozconfig

    - name: Build Firefox
      run: ./mach build

    - name: Archive build output
      run: |
        mkdir -p output
        cp -r obj-x86_64-pc-linux-gnu/dist output/firefox-dist
        zip -r firefox-build.zip output/firefox-dist

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: firefox-build
        path: firefox-build.zip
